### ISSUE TITLE
bundle name mismatch

### ISSUE THREAD

**Issue by Cethy** [WandiParis/EasyAdminPlusBundle#1]
When you (from README)
```sh
composer require wandi/easyadminplus-bundle
```
composer pulls a bundle tagged `0.0.1` and will not trigger the recipe for sf4.

After some digging, I found that you registered this bundle in packagist with the name `wandi/easyadmin-plus-bundle`.

```sh
composer require wandi/easyadmin-plus-bundle
```
works as expected.

**Comment by jacquesndl** [comment]
Thanks for your feedback @Cethy .
I will update the documentation as soon as possible.
