### ISSUE TITLE
What about adding Filter in your bundle ?

### ISSUE THREAD

**Issue by sebheitzmann** [WandiParis/EasyAdminPlusBundle#10]
I'm currently looking for a EasyAdmin extension to add Multi field Filtering. Maybe it could be better to have only one extension bundle. 

Do you work on something like this ? Or can i Make a pull request when I'm done ?

Thanks for any info.

**Comment by laurent-bientz** [comment]
Hey @sebheitzmann, we currently have no plan about implementing multi field filtering so it can be a nice feature.

How do u imagine this feature functionally and graphically?

Adding X filters one by one? and specify the comparison operator for each? (equal, like, greather than, etc.)

How to do cumulate the X filters to the dql? **AND**/**OR** 
```sql
# two filters give ?
WHERE A = ? AND B = ?
```

How do u imagine the form type for this kind of feature?

If it can help you, here is a caption of a previous admin coded from scratch in which we've this feature:
![admin](https://user-images.githubusercontent.com/6093572/40923697-c63f3792-6815-11e8-9f7b-5ad5b06742e8.jpg)

Cheers

**Comment by sebheitzmann** [comment]
Hi, 

sorry for the late response. 

About the filter, we used to make AND combination of the filter fields. I think that it's the most valuable use case. If the user need an OR he can do multiple search.

please have a look at https://github.com/2lenet/EasyAdminPlusBundle/blob/master/doc/chapter-6.md

It's what we currently implement. It's not really done for all filter type but the basic is working.

**Comment by laurent-bientz** [comment]
Hi @sebheitzmann, it sounds to be a good start.

Why directly not using the namespace in the yaml for the correct type? and guess automatically the correct type based on the guessed EasyAdmin's type?

Feel free to submit a PR when the job is improved!

Cheers

**Comment by sebheitzmann** [comment]
The namespace is possible. But for embedded type i find that more user friendly to add thé namespace automaticcaly.
