### ISSUE TITLE
Error on generate entities

### ISSUE THREAD

**Issue by jbchateaux** [WandiParis/EasyAdminPlusBundle#12]
Hello,

I installed and followed the first part about authentication.
However during the second part on the generator, I get an error while trying to use
**php bin/console wandi:easy-admin-plus:generator:generate**

The error:

> In PropertyTypeHelper.php line 179:
> Notice: Undefined index: EasyAdminType

Thanks by advance for your help !

Cheers
JB.

**Comment by kasou** [comment]
Hello,

Thank you for reporting this issue, it's patched [0.6.3](https://github.com/WandiParis/EasyAdminPlusBundle/tree/0.6.3)

kasou
