### ISSUE TITLE
You have requested a non-existent service 

### ISSUE THREAD

**Issue by pesseyjulien** [WandiParis/EasyAdminPlusBundle#23]
Hi,

After following the install instruction, I'm getting the following error when I try to display the admin :

You have requested a non-existent service "wandi.easy_admin_plus.acl.security.admin_authorization_checker".

Thanks in advance for your help,
Julien

**Comment by pesseyjulien** [comment]
Just realized it requires SF4 while I'm on SF3, so I think that might be it.. Sorry !

**Comment by laurent-bientz** [comment]
No problem
