### ISSUE TITLE
Using multiple extensions with EasyAdmin

### ISSUE THREAD

**Issue by DylanKas** [WandiParis/EasyAdminPlusBundle#30]
Hello!

We decided to use this bundle for our project especially for the export function.

We are trying to use some features from another EasyAdmin Extension ([AlterPHP](https://github.com/alterphp/EasyAdminExtensionBundle)) as well but we face some issues configurating both of them at the same time.

I contacted the author of AlterPHP/EasyAdminExtensionBundle and we modified the controller to use a trait so that you can just use it in your custom controller instead of having your class extends your controller. It's very useful since multiple extensions want you to extends their controller so it's better to be able to use it's trait.

I may not be really clear about what I'm saying so you could[ look up the issue I posted on AlterPHP](https://github.com/alterphp/EasyAdminExtensionBundle/issues/175) :

Would you be okay if I modified it just like [this PR](https://github.com/alterphp/EasyAdminExtensionBundle/pull/176) and made one for your extension ?

Thanks in advance.

**Comment by laurent-bientz** [comment]
Hello @DylanKas 

Sounds good. If you can submit a PR which relocate our Controller code in a Trait, I'll take a look later to merge it.

Thanks

**Comment by DylanKas** [comment]
Thanks for the quick response, I just submitted a PR for those changes and it works well.

**Comment by laurent-bientz** [comment]
I saw, if you can just remove the unused `use` statement in the `Trait`, it'll be great!

**Comment by laurent-bientz** [comment]
Thanks @DylanKas!

It's merged and released in [2.0.2 tag](https://github.com/WandiParis/EasyAdminPlusBundle/releases/tag/2.0.2)

Have a nice day!
