### ISSUE TITLE
Issue on install and cache:clear

### ISSUE THREAD

**Issue by linkito87** [WandiParis/EasyAdminPlusBundle#32]
I have an error when execute the cac:cle after install the plugin. I have the PHP version 7.3. This is the error:

`!!  ArgumentCountError {#5649
!!    #message: "Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /Users/hectorsantosmejias/Work/Pixea/Caminos60/web/vendor/wandi/easyadmin-plus-bundle/src/DependencyInjection/Configuration.php on line 21 and at least 1 expected"
!!    #code: 0
!!    #file: "./vendor/symfony/config/Definition/Builder/TreeBuilder.php"
!!    #line: 26
!!    trace: {
!!      ./vendor/symfony/config/Definition/Builder/TreeBuilder.php:26 { …}
!!      ./vendor/wandi/easyadmin-plus-bundle/src/DependencyInjection/Configuration.php:21 { …}
!!      ./vendor/symfony/config/Definition/Processor.php:50 { …}
!!      ./vendor/wandi/easyadmin-plus-bundle/src/DependencyInjection/WandiEasyAdminPlusExtension.php:24 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:734 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:545 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:126 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:169 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:75 { …}
!!      ./vendor/symfony/console/Application.php:141 { …}
!!      ./bin/console:42 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!        arguments: {
!!          $input: Symfony\Component\Console\Input\ArgvInput {#3 …}
!!        }
!!      }
!!    }
!!  }
!!  
`

**Comment by laurent-bientz** [comment]
Hello @linkito87 

Yes it's because they changed the TreeBuilder prototype in Symfony 5:

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0`

You can rollback to Symfony 4.x to ensure it's working or send a PR to fix the compatibility with Symfony 5, feel free to take a look at https://github.com/KnpLabs/DoctrineBehaviors/pull/411

**Comment by laurent-bientz** [comment]
@linkito87 compatibility with sf5 should be fixed thanks to [ad846d8](https://github.com/WandiParis/EasyAdminPlusBundle/commit/ad846d8d193f18e4da1b1bf8f6b58b29a46b467c)

**Comment by linkito87** [comment]
> @linkito87 compatibility with sf5 should be fixed thanks to [ad846d8](https://github.com/WandiParis/EasyAdminPlusBundle/commit/ad846d8d193f18e4da1b1bf8f6b58b29a46b467c)

Thanks! I wait for it :)

**Comment by laurent-bientz** [comment]
Just run a `composer update wandi/easyadmin-plus-bundle` and everything should be fine!
