### ISSUE TITLE
Virtual properties are always null in export

### ISSUE THREAD

**Issue by youngdolphin** [WandiParis/EasyAdminPlusBundle#34]
My Alpha class has a property Beta which is a ManyToOne with the Beta class. I'm trying to include some fields of this Beta property in the export of the Alpha class but everything i've tried results in null.
I've tried:

```
export:
    fields:
        - { property: 'beta.id', label: 'Beta ID' }
```

And i've tried to add a public method getBetaId() in the Alpha class, then in the export i add it as it says in the EasyAdmin documentation on how to add a virtual property (https://symfony.com/doc/1.x/bundles/EasyAdminBundle/book/list-search-show-configuration.html#virtual-properties) because in the documentation of EasyAdminPlus it's told that export works like list:
```
export:
    fields:
        - { property: 'betaId', label: 'Beta ID' }
```

Is there a way to export a virtual property?

**Comment by laurent-bientz** [comment]
Hey,

Unfortunately, there is no possibility to display properties from another joined entities. It's the same in the EasyAdmin list action, you can only display the relation itself thanks to the __toString() implementation.

So instead of trying to export beta.id, you can just try to export 'beta' and it'll call Beta::__toString()

**Comment by youngdolphin** [comment]
Sorry but if i create a public method like getBetaProperty1() that returns $this->beta->getProperty1() in the Alpha class and in the list i write the field "betaProperty1" it is shown correctly in the list view. Isn't there the same logic in the export?

**Comment by youngdolphin** [comment]
Sorry for the late answer, i've just tested it and it works as expected! Thanks a lot!

**Comment by laurent-bientz** [comment]
I'm glad, thx for your feebacks.
