### ISSUE TITLE
Auth - Add a role param

### ISSUE THREAD

**Issue by laurent-bientz** [WandiParis/EasyAdminPlusBundle#4]
@jacquesndl 

We need a `roles` param into the command `wandi:easy-admin-plus:user:create`

```shell
php bin/console wandi:easy-admin-plus:user:create --username=jacques --password=pwd --roles=[ROLE_ADMIN]
```

It'll be also nice to have a new cmd to change admin roles

```shell
`wandi:easy-admin-plus:user:change-roles` --username=jacques --roles=[ROLE_USER]
```

 :stuck_out_tongue:

**Comment by jacquesndl** [comment]
@laurent-bientz 

This feature has been added on the [0.4.2](https://github.com/WandiParis/EasyAdminPlusBundle/tree/0.4.2).
See the [documentation](https://github.com/WandiParis/EasyAdminPlusBundle/blob/0.4.2/doc/chapter-1.md) for the commands' description.
